EXE_BOINC = prst_boinc

VCPKG_DIR = ../../vcpkg/installed/x64-osx
BOINC_INC = -I$(VCPKG_DIR)/include/boinc
BOINC_LIB = -L$(VCPKG_DIR)/lib -lboincapi -lboinc

all_boinc: $(EXE_BOINC)
.PHONY: all_boinc

include Makefile

$(EXE_BOINC): $(COMPOBJS_COMMON) prst_boinc.o bow.o boinc.o
	$(CXX) $(CXXFLAGS) $(LFLAGS) -o $@ $^ $(LIB_GWNUM) $(BOINC_LIB)

prst_boinc.o: prst.cpp
	$(CXX) -o $@ -c $(CXXFLAGS) -DBOINC $<

boinc.o: boinc.cpp
	$(CXX) -o $@ -c $(CXXFLAGS) -DBOINC $<

bow.o: bow/bow.cpp
	$(CXX) -o $@ -c $(CXXFLAGS) $(BOINC_INC) $<
